(in-package :plan-lib)

(def-goal (achieve (container-opened ?loc ?degree))
  (ros-info (achieve plan-lib) "(achieve (container-opened))")
  (with-designators
      ((open-loc (location `((to open)
                             (location ,?loc))))
       (open-action (action `((type trajectory)
                              (to open) (location ,?loc)
                              (degree ,?degree)))))
    (at-location (open-loc)
      (perform open-action)))
  ?loc)

(def-goal (achieve (container-closed ?loc ?degree))
  (ros-info (achieve plan-lib) "(achieve (container-closed))")
  (with-designators
      ((close-loc (location `((to close)
                              (location ,?loc))))
       (close-action (action `((type trajectory)
                              (to close) (location ,?loc)
                              (degree ,?degree)))))
    (at-location (close-loc)
      (perform close-action)))
  ?loc)
